name: build pipeline
on:
  # Manually trigger from Actions tab
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION:  "us-east-1"
  
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository 
      - uses: actions/checkout@v3
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Setup the build tools 
        run: |
           curl -L https://releases.hashicorp.com/packer/1.8.2/packer_1.8.2_windows_amd64.zip -o packer.zip
           unzip packer.zip
           echo "packer version - $(packer --version)"
      - name: Validate the config 
        run: packer validate goldenimage.pkr.hcl
